

package com.lingh.type;

public enum ShardingType {
    
    SHARDING_DATABASES,
    
    SHARDING_TABLES,
    
    SHARDING_DATABASES_AND_TABLES,
    
    SHARDING_SHADOW_DATABASES,
    
    ENCRYPT_SHADOW,
    
    READWRITE_SPLITTING,
    
    READWRITE_SPLITTING_SHADOW,
    
    SHARDING_READWRITE_SPLITTING,
    
    ENCRYPT,
    
    SHADOW,
    
    SHADOW_DEFAULT_ALGORITHM,
    
    SHARDING_AUTO_TABLES,
    
    SHARDING_HINT_DATABASES_ONLY,
    
    SHARDING_HINT_DATABASES_TABLES,
    
    READWRITE_SPLITTING_HINT,
    
    SHARDING_DATABASES_INTERVAL
}
