package com.lingh.type;

public enum ShardingType {
    
    SHARDING_DATABASES,
    
    SHARDING_TABLES,
    
    SHARDING_DATABASES_AND_TABLES,
    
    SHARDING_AUTO_TABLES,
    
    SHARDING_HINT_DATABASES_ONLY,
    
    SHARDING_HINT_DATABASES_TABLES,
    
    SHARDING_DATABASES_INTERVAL
}
