

CREATE TABLE IF NOT EXISTS t_role (id INT NOT NULL AUTO_INCREMENT, user_name VARCHAR(45) NULL, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS t_product (id INT NOT NULL AUTO_INCREMENT, product_name VARCHAR(45) NULL, PRIMARY KEY (id));
